SELECT title, release_year FROM moviesdb.movies  where studio="marvel studios";
SELECT * FROM moviesdb.movies  where title like "%Avenge%";
SELECT release_year FROM moviesdb.movies  where title like "%The Godfather%";
SELECT distinct studio from moviesdb.movies  where industry="bollywood";
SELECT * FROM moviesdb.movies  where imdb_rating >= 9;
SELECT * FROM moviesdb.movies  where imdb_rating <= 5;
SELECT * FROM moviesdb.movies  where imdb_rating >= 6 and imdb_rating <=8;
SELECT * FROM moviesdb.movies  where imdb_rating between 6 and 8;
SELECT * FROM moviesdb.movies  where release_year=2022 or  release_year=2019 or release_year=2018;
SELECT * FROM moviesdb.movies  where release_year in (2022,2019,2018);
SELECT * FROM moviesdb.movies  where studio in ("hombale films","Marvel Studios");
SELECT * FROM moviesdb.movies  where imdb_rating is null;
SELECT * FROM moviesdb.movies  where imdb_rating is not null;
SELECT * FROM moviesdb.movies  where industry="bollywood" order by imdb_rating;
SELECT * FROM moviesdb.movies  where industry="bollywood" order by imdb_rating desc limit 3;
SELECT * FROM moviesdb.movies  where industry="bollywood" order by imdb_rating desc limit 3 offset 2;
SELECT * FROM moviesdb.movies order by release_year desc;
SELECT * FROM moviesdb.movies where release_year=2022;
SELECT * FROM moviesdb.movies where release_year>2020;
SELECT * FROM moviesdb.movies where release_year>2020 and imdb_rating >8;
SELECT * FROM moviesdb.movies  where studio in ("hombale films","Marvel Studios");
SELECT title, release_year FROM moviesdb.movies  where title like "%thor%";
SELECT * FROM moviesdb.movies  where studio not in ("Marvel Studios");
SELECT * FROM moviesdb.movies  where studio !="Marvel Studios";